### PR TITLE
Users upload files

### PR DESCRIPTION
**Pull request by giovanni-orciuolo**
This commit implements the `/invoke` endpoint to output JSON and graph images from input data

### CODE REVIEW

**Comment by giovanni-orciuolo** [comment]
I rebased commits from other branches to align and it made a lot of duplicates, I think I need to cleanup before opening the PR... any help is appreciated. The relevant commit is https://github.com/production-optimiser/production-optimiser/pull/16/commits/b8740d486c3c38e7cb00edae3fa2d082641ce3fa

**Review by f-hruza0111 — APPROVED** [review]
Seems fine for now, we are missing logic to save input data and map it to the results but that can be done in next sprint

**Comment by f-hruza0111** [comment]
Resolved conflict but it seems to have messed up the formatting

**Comment by Theanko1412** [comment]
lgmt, refactoring is definitely needed in the next spring or 2 max

**Comment by Theanko1412** [comment]
maybe wait with merge for other PRs to go into develop first, since you had a lot of changes and we dont have tests to not break something

**Comment by giovanni-orciuolo** [comment]
@Theanko1412 I'm opening another branch, wait for that PR to merge it into develop

**Pull request closed without merging**
